config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trainings
  root 'trainings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/training.rb
class Training < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController

    def index
    end

    def new
    end

    def create
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kayak</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trainings/index.html.erb
<h1>This is <%= @title %></h1>

<p><%= @text %></p>
<br />
<p><a href="<%= new_training_path %>">Enter new training</a>.</p>

app/views/trainings/new.html.erb
<h1>This is <%= @title %></h1>

<p><%= @text %></p>
<br />

<%= form_for :training do |f| %>
    <ul>
        <li><%= f.label :date %>
            <%= f.datetime_field :date %>
        </li>
        <li>
            <%= f.label :name %>
            <%= f.text_field :name, limit: 10 %>
        </li>
        <li><%= f.submit %></li>
    </ul>
<% end %>